name: Build and upload wheels

on:
  push:
    branches: 
      - '*'
  pull_request:
    branches: 
      - '*'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-2019, ubuntu-18.04, macos-10.15]
        python-version: [3.6, 3.7, 3.8, 3.9]

    steps:
      - uses: actions/checkout@v1
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: pip install wheel setuptools

      - name: Build wheel
        run: python setup.py bdist_wheel --universal

      - name: Install software
        run: pip install --find-links=${{github.workspace}}/dist/ faststainnorm

      - name: Test CLI
        run: faststainnorm --help

      - name: Test inference
        run: faststainnorm --ref misc/easy.png --img misc/hard.png

      - name: Setup batch mode sample
        run: |
          mkdir test-samples
          for i in $(seq 1 10); do cp misc/easy.png test-samples/easy-{}.png; done
          ls test-samples

      - name: Upload Python wheel
        uses: actions/upload-artifact@v2
        with:
          name: Python wheel
          path: ${{github.workspace}}/dist/faststainnorm-*.whl
          if-no-files-found: error